project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Pengxuan Zhu"
  site-url: https://HydrometeorologyZhu.github.io/
  favicon: images/mylogo.png
  repo-url: https://github.com/lianyujun/lianyujun.github.io
  repo-actions: [edit, issue]
  
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Blog/Notes"
        href: blog.qmd
      - text: "Life"
        href: life.qmd


format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细